name: Upstream sync

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout snapshot
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          ref: snapshot
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/KevinOConnor/klipper.git
          git fetch upstream master
      - name: Merge changes
        id: merge
        run: |
          echo "::set-output name=status::success"
          git config user.name Desuuuu
          git config user.email Desuuuu@users.noreply.github.com
          git merge --no-commit --no-ff upstream/master
          git commit -m "Merge upstream changes" || echo "::set-output name=status::failure"
      - name: Push changes
        if: steps.merge.outputs.status == 'success'
        run: |
          git push origin snapshot
      - name: Create tag
        if: steps.merge.outputs.status == 'success'
        run: |
          export TAGNAME=snapshot-$(date +'%y%m%d')
          git tag -m '/!\ This is an automated, untested release. Use at your own risk /!\' $TAGNAME
          git push origin refs/tags/$TAGNAME
